This notebook performs alpha motor neuron subtype label transfer from the multiome RNA data to the RNA-only data and also performs pseudobulk differential expression analyses using the multiome RNA data.

## Setup

In [1]:
# Set paths
SOD1_RENV_RNA="/oak/stanford/groups/agitler/Shared/Shared_Jupyter_Notebook_Analysis/4.1.1-OG-RNA/"
renv::load(SOD1_RENV_RNA)

In [2]:
# Load packages
suppressPackageStartupMessages({
  library(Seurat)
  library(SoupX)
  library(ggplot2)
  library(dplyr)
  library(BiocParallel)
  library(scDblFinder)
  library(svglite)
  library(pheatmap)
  library(matrixStats)
  library(tibble)
  library(DESeq2)
  library(VennDiagram)
  library(grid)
  library(stringr)
  library(ggrepel)
  library(ggrastr)
  library(ggpubr)
  library(forcats)
  library(ggbreak)
  library(cowplot)
  library(colorspace)
  library(broom)
  library(colorspace)
  library(ArchR)
})

                                                   / |
                                                 /    \
            .                                  /      |.
            \\\                              /        |.
              \\\                          /           `|.
                \\\                      /              |.
                  \                    /                |\
                  \\#####\           /                  ||
                ==###########>      /                   ||
                 \\##==......\    /                     ||
            ______ =       =|__ /__                     ||      \\\
        ,--' ,----`-,__ ___/'  --,-`-===================##========>
       \               '        ##_______ _____ ,--,__,=##,__   ///
        ,    __==    ___,-,__,--'#'  ==='      `-'    | ##,-/
        -,____,---'       \\####\\________________,--\\_##,/
           ___      .______        ______  __    __  .______
          /   \     |   _  \      /      ||  |  |  | |   _  \
         /  ^  \    |  |_)  |    |  ,----'|  |__|  | |  |_)  |
        /  /_\  \   |      /     |  |     |   __   | |      /
       /  _____  \  |  |\  \\___ |  `----.|  |  |  | |  |\  \\___.
      /__/     \__\ | _| `._____| \______||__|  |__| | _| `._____|

## Directory to save output

In [3]:
save_dir <- '/oak/stanford/groups/agitler/Shared/SOD1_Paper/RNA/'

## Make Seurat object from multiome RNA data

In [31]:
#Load ArchR Project for alpha MNs
proj_all_dr <- loadArchRProject('/oak/stanford/groups/agitler/Shared/SOD1_Paper/Multiome/proj_all_dr')

Successfully loaded ArchRProject!


                                                   / |
                                                 /    \
            .                                  /      |.
            \\\                              /        |.
              \\\                          /           `|.
                \\\                      /              |.
                  \                    /                |\
                  \\#####\           /                  ||
                ==###########>      /                   ||
                 \\##==......\    /                     ||
            ______ =       =|__ /__                     ||      \\\
        ,--' ,----`-,__ ___/'  --,-`-===================##========>
       \               '        ##_______ _____ ,--,__,=##,__   ///
        ,    __==    ___,-,__,--'#'  ==='      `-'    | ##,-/
        -,____,---'       \\####\\________________,--\\_##,/
           ___      .______        ______  __    __  .______
          /   \     |   _  \      /      ||  |  |  | |   _  \
         /  ^  \    |  |_)  |    |  ,----'|  |__|  | |  |_)  |
        /  /_\  \   |      /     |  |     |   __   | |      /
       /  _____  \  |  |\  \\___ |  `----.|  |  |  | |  |\  \\___.
      /__/     \__\ | _| `._____| \______||__|  |__| | _| `._____|

In [32]:
# Extract metadata
metadata <- getCellColData(proj_all_dr) %>% as.data.frame()

In [33]:
#Get Input RNA Files
sample1_rna <- '/oak/stanford/groups/agitler/Olivia/single_cell_data/10X_analyzed/SOD1_multiome/5_25_sample1/outs/filtered_feature_bc_matrix.h5'
sample2_rna <- '/oak/stanford/groups/agitler/Olivia/single_cell_data/10X_analyzed/SOD1_multiome/6_3_sample1/outs/filtered_feature_bc_matrix.h5'
sample3_rna <- '/oak/stanford/groups/agitler/Olivia/single_cell_data/10X_analyzed/SOD1_multiome/6_3_sample2/outs/filtered_feature_bc_matrix.h5'
sample4_rna <- '/oak/stanford/groups/agitler/Olivia/single_cell_data/10X_analyzed/SOD1_multiome/12_22_sample1/outs/filtered_feature_bc_matrix.h5'
sample5_rna <- '/oak/stanford/groups/agitler/Olivia/single_cell_data/10X_analyzed/SOD1_multiome/12_22_sample2/outs/filtered_feature_bc_matrix.h5'

inputFiles_rna <- c(sample1_5_25=sample1_rna, sample1_6_3=sample2_rna, sample2_6_3=sample3_rna, sample1_12_22=sample4_rna, sample2_12_22=sample5_rna)

In [34]:
# Import scRNA
seRNA <- import10xFeatureMatrix(
    input = inputFiles_rna,
    names = names(inputFiles_rna),
    strictMatch = FALSE
)

Importing Feature Matrix 1 of 5

Importing Feature Matrix 2 of 5

Importing Feature Matrix 3 of 5

Importing Feature Matrix 4 of 5

Importing Feature Matrix 5 of 5

Re-ordering RNA matricies for consistency.

Merging individual RNA objects...


Merging sample1_6_3

Warning! Some values within column "id" of the rowData (gene metadata) of your objects do not precisely match!

This is often caused by slight variations in Ensembl IDs and gene locations used by cellranger across different samples. ArchR will ignore these mismatches and allow merging to proceed but you should check to make sure that these are ok for your data.


Mismatch in column "id" row 25927 for sample1_6_3: ENSMUSG00000116160 does not exactly match ENSMUSG00000116253!

strictMatch = FALSE so mismatching information will be coerced to match the first sample provided.


Merging sample2_6_3

Warning! Some values within column "id" of the rowData (gene metadata) of your objects do not precisely match!

This is often caused by slight variations in Ensembl IDs and gene locations used by cellranger across different samples. ArchR will ignore these mismatches and allow merging to proceed but you should check to make sure that these are ok for your data.


Mismatch in column "id" row 25927 for sample2_6_3: ENSMUSG00000116160 does not exactly match ENSMUSG00000116253!

strictMatch = FALSE so mismatching information will be coerced to match the first sample provided.


Merging sample1_12_22

Warning! Some values within column "id" of the rowData (gene metadata) of your objects do not precisely match!

This is often caused by slight variations in Ensembl IDs and gene locations used by cellranger across different samples. ArchR will ignore these mismatches and allow merging to proceed but you should check to make sure that these are ok for your data.


Mismatch in column "id" row 14961 for sample1_12_22: ENSMUSG00000053687 does not exactly match ENSMUSG00000115067!

strictMatch = FALSE so mismatching information will be coerced to match the first sample provided.

Mismatch in column "id" row 25927 for sample1_12_22: ENSMUSG00000116160 does not exactly match ENSMUSG00000116253!

strictMatch = FALSE so mismatching information will be coerced to match the first sample provided.


Merging sample2_12_22

Warning! Some values within column "id" of the rowData (gene metadata) of your objects do not precisely match!

This is often caused by slight variations in Ensembl IDs and gene locations used by cellranger across different samples. ArchR will ignore these mismatches and allow merging to proceed but you should check to make sure that these are ok for your data.


Mismatch in column "id" row 14961 for sample2_12_22: ENSMUSG00000053687 does not exactly match ENSMUSG00000115067!

strictMatch = FALSE so mismatching information will be coerced to match the first sample provided.

Mismatch in column "id" row 25927 for sample2_12_22: ENSMUSG00000116160 does not exactly match ENSMUSG00000116253!

strictMatch = FALSE so mismatching information will be coerced to match the first sample provided.

In [35]:
# Get the counts data as a sparse matrix
counts_matrix <- assay(seRNA, "counts")

# Extract the column names of the sparse matrix
nuclei_names <- colnames(counts_matrix)

# Filter the column names based on whether they are in the row names of metadata
filtered_nuclei <- nuclei_names[nuclei_names %in% rownames(metadata)]

# Subset the sparse matrix to retain only the filtered columns
filtered_counts_matrix <- counts_matrix[, filtered_nuclei]

In [36]:
# Create the Seurat object
proj_all_dr_multiome_rna_sobj <- CreateSeuratObject(counts = filtered_counts_matrix)

# Add metadata to the Seurat object
proj_all_dr_multiome_rna_sobj <- AddMetaData(object = proj_all_dr_multiome_rna_sobj, metadata = metadata)

# Verify the Seurat object
proj_all_dr_multiome_rna_sobj

An object of class Seurat
32233 features across 26965 samples within 1 assay
Active assay: RNA (32233 features, 0 variable features)

In [37]:
proj_all_dr_multiome_rna_sobj@meta.data$orig.ident <- proj_all_dr_multiome_rna_sobj@meta.data$Sample

In [38]:
saveRDS(proj_all_dr_multiome_rna_sobj, file = paste0(save_dir, 'rds_files/proj_all_dr_multiome_rna_sobj.rds'))

## Alpha MN subtype label transfer from multiome to RNA-only alpha MNs

In [5]:
#Load ArchR Project for alpha MNs
proj_alpha <- loadArchRProject('/oak/stanford/groups/agitler/Shared/SOD1_Paper/Multiome/proj_alpha')

Successfully loaded ArchRProject!


                                                   / |
                                                 /    \
            .                                  /      |.
            \\\                              /        |.
              \\\                          /           `|.
                \\\                      /              |.
                  \                    /                |\
                  \\#####\           /                  ||
                ==###########>      /                   ||
                 \\##==......\    /                     ||
            ______ =       =|__ /__                     ||      \\\
        ,--' ,----`-,__ ___/'  --,-`-===================##========>
       \               '        ##_______ _____ ,--,__,=##,__   ///
        ,    __==    ___,-,__,--'#'  ==='      `-'    | ##,-/
        -,____,---'       \\####\\________________,--\\_##,/
           ___      .______        ______  __    __  .______
          /   \     |   _  \      /      ||  |  |  | |   _  \
         /  ^  \    |  |_)  |    |  ,----'|  |__|  | |  |_)  |
        /  /_\  \   |      /     |  |     |   __   | |      /
       /  _____  \  |  |\  \\___ |  `----.|  |  |  | |  |\  \\___.
      /__/     \__\ | _| `._____| \______||__|  |__| | _| `._____|

In [6]:
# Extract metadata
metadata <- getCellColData(proj_alpha) %>% as.data.frame()

In [7]:
#Get Input RNA Files
sample1_rna <- '/oak/stanford/groups/agitler/Olivia/single_cell_data/10X_analyzed/SOD1_multiome/5_25_sample1/outs/filtered_feature_bc_matrix.h5'
sample2_rna <- '/oak/stanford/groups/agitler/Olivia/single_cell_data/10X_analyzed/SOD1_multiome/6_3_sample1/outs/filtered_feature_bc_matrix.h5'
sample3_rna <- '/oak/stanford/groups/agitler/Olivia/single_cell_data/10X_analyzed/SOD1_multiome/6_3_sample2/outs/filtered_feature_bc_matrix.h5'
sample4_rna <- '/oak/stanford/groups/agitler/Olivia/single_cell_data/10X_analyzed/SOD1_multiome/12_22_sample1/outs/filtered_feature_bc_matrix.h5'
sample5_rna <- '/oak/stanford/groups/agitler/Olivia/single_cell_data/10X_analyzed/SOD1_multiome/12_22_sample2/outs/filtered_feature_bc_matrix.h5'

inputFiles_rna <- c(sample1_5_25=sample1_rna, sample1_6_3=sample2_rna, sample2_6_3=sample3_rna, sample1_12_22=sample4_rna, sample2_12_22=sample5_rna)

In [8]:
# Import scRNA
seRNA <- import10xFeatureMatrix(
    input = inputFiles_rna,
    names = names(inputFiles_rna),
    strictMatch = FALSE
)

Importing Feature Matrix 1 of 5

Importing Feature Matrix 2 of 5

Importing Feature Matrix 3 of 5

Importing Feature Matrix 4 of 5

Importing Feature Matrix 5 of 5

Re-ordering RNA matricies for consistency.

Merging individual RNA objects...


Merging sample1_6_3

Warning! Some values within column "id" of the rowData (gene metadata) of your objects do not precisely match!

This is often caused by slight variations in Ensembl IDs and gene locations used by cellranger across different samples. ArchR will ignore these mismatches and allow merging to proceed but you should check to make sure that these are ok for your data.


Mismatch in column "id" row 25927 for sample1_6_3: ENSMUSG00000116160 does not exactly match ENSMUSG00000116253!

strictMatch = FALSE so mismatching information will be coerced to match the first sample provided.


Merging sample2_6_3

Warning! Some values within column "id" of the rowData (gene metadata) of your objects do not precisely match!

This is often caused by slight variations in Ensembl IDs and gene locations used by cellranger across different samples. ArchR will ignore these mismatches and allow merging to proceed but you should check to make sure that these are ok for your data.


Mismatch in column "id" row 25927 for sample2_6_3: ENSMUSG00000116160 does not exactly match ENSMUSG00000116253!

strictMatch = FALSE so mismatching information will be coerced to match the first sample provided.


Merging sample1_12_22

Warning! Some values within column "id" of the rowData (gene metadata) of your objects do not precisely match!

This is often caused by slight variations in Ensembl IDs and gene locations used by cellranger across different samples. ArchR will ignore these mismatches and allow merging to proceed but you should check to make sure that these are ok for your data.


Mismatch in column "id" row 14961 for sample1_12_22: ENSMUSG00000053687 does not exactly match ENSMUSG00000115067!

strictMatch = FALSE so mismatching information will be coerced to match the first sample provided.

Mismatch in column "id" row 25927 for sample1_12_22: ENSMUSG00000116160 does not exactly match ENSMUSG00000116253!

strictMatch = FALSE so mismatching information will be coerced to match the first sample provided.


Merging sample2_12_22

Warning! Some values within column "id" of the rowData (gene metadata) of your objects do not precisely match!

This is often caused by slight variations in Ensembl IDs and gene locations used by cellranger across different samples. ArchR will ignore these mismatches and allow merging to proceed but you should check to make sure that these are ok for your data.


Mismatch in column "id" row 14961 for sample2_12_22: ENSMUSG00000053687 does not exactly match ENSMUSG00000115067!

strictMatch = FALSE so mismatching information will be coerced to match the first sample provided.

Mismatch in column "id" row 25927 for sample2_12_22: ENSMUSG00000116160 does not exactly match ENSMUSG00000116253!

strictMatch = FALSE so mismatching information will be coerced to match the first sample provided.

In [9]:
# Get the counts data as a sparse matrix
counts_matrix <- assay(seRNA, "counts")

# Extract the column names of the sparse matrix
nuclei_names <- colnames(counts_matrix)

# Filter the column names based on whether they are in the row names of metadata
filtered_nuclei <- nuclei_names[nuclei_names %in% rownames(metadata)]

# Subset the sparse matrix to retain only the filtered columns
filtered_counts_matrix <- counts_matrix[, filtered_nuclei]

In [10]:
# Create the Seurat object
alpha_multiome_rna_sobj <- CreateSeuratObject(counts = filtered_counts_matrix)

# Add metadata to the Seurat object
alpha_multiome_rna_sobj <- AddMetaData(object = alpha_multiome_rna_sobj, metadata = metadata)

# Verify the Seurat object
alpha_multiome_rna_sobj

An object of class Seurat
32233 features across 3433 samples within 1 assay
Active assay: RNA (32233 features, 0 variable features)

In [11]:
alpha_multiome_rna_sobj@meta.data$orig.ident <- alpha_multiome_rna_sobj@meta.data$Sample
alpha_multiome_rna_sobj <- NormalizeData(alpha_multiome_rna_sobj)
alpha_multiome_rna_sobj <- FindVariableFeatures(alpha_multiome_rna_sobj, selection.method = "vst", nfeatures = 2000)

In [12]:
saveRDS(alpha_multiome_rna_sobj, file = paste0(save_dir, 'rds_files/alpha_multiome_rna_sobj.rds'))

In [13]:
# Load alpha MN RNA Seurat object
alpha_subset <- readRDS(file = paste0(save_dir, 'rds_files/alpha_subset.rds'))

In [14]:
alpha.anchors <- FindTransferAnchors(reference = alpha_multiome_rna_sobj, query = alpha_subset, 
    reference.assay = "RNA", query.assay = "RNA", dims = 1:50)
predictions <- TransferData(anchorset = alpha.anchors, refdata = alpha_multiome_rna_sobj$alpha_subtype, 
    dims = 1:50)
alpha_label_transfer_50 <- AddMetaData(alpha_subset, metadata = predictions)

Warning message:
“npcs is smaller than the largest value requested by the dims parameter.
Setting npcs to 50 and continuing.”
Performing PCA on the provided reference using 1898 features as input.

Projecting cell embeddings

Finding neighborhoods

Finding anchors

	Found 7146 anchors

Filtering anchors

	Retained 5268 anchors

Finding integration vectors

Finding integration vector weights

Predicting cell labels

In [15]:
saveRDS(alpha_label_transfer_50, file = paste0(save_dir, 'rds_files/alpha_label_transfer_50.rds'))

## DESeq2 differential expression analysis helper function

In [4]:
prepare_counts <- function(seurat_object, test.category, by.category, min.nuclei) {
    seurat_object$samples <- paste0(seurat_object@meta.data[, test.category], "_", seurat_object$orig.ident)
    
    # Aggregate counts for each sample
    counts <- AggregateExpression(seurat_object, 
                    group.by = c(by.category, "samples"),
                    assays = "RNA",
                    slot = "counts",
                    return.seurat = FALSE)
    
    counts <- counts$RNA
    
    # Transpose counts and convert to data frame
    counts.t.df <- as.data.frame(t(counts))
    
    # Get samples to delete (number of nuclei < min.nuclei)
    # 1. Get table containing nuclei counts for each sample/by.category pair
    nuclei_count_table <- table(seurat_object@meta.data[, by.category], seurat_object$samples)
    
    # 2. Get row names (by.category) and column names (samples)
    by_category <- rownames(nuclei_count_table)
    samples <- colnames(nuclei_count_table)

    # 3. Iterate over all combinations, check the condition, and store samples to delete in the vector
    to_delete <- c()

    for (i in by_category) {
      for (j in samples) {
        value <- nuclei_count_table[i, j]
        if (value < min.nuclei) {
          to_delete <- c(to_delete, paste(i, j, sep = "_"))
        }
      }
    }
    
    # 4. Filter out sample/by.category pairs with fewer than min.nuclei 
    counts.t.df <- counts.t.df %>% filter(!row.names(.) %in% to_delete)
    
    # Split data frame by by.category
    splitRows <- sub("_.*", "", rownames(counts.t.df))
    counts.split <- split.data.frame(counts.t.df, f = factor(splitRows)) 
    
    # For every element in counts.split, remove by.category from the row names and then transpose
    counts.split <- lapply(counts.split, function(x){
    rownames(x) <- sub("^[^_]*_", "", rownames(x))
    t(x)
    })
    
}

## Multiome RNA DESeq2 analyses

### DM/DAMN vs. nonDM/DAMN from the multiome RNA data
alpha_multiome_RNA_nonDAMN_vs_DAMN.csv

In [5]:
alpha_multiome_rna_sobj <- readRDS(file = paste0(save_dir, 'rds_files/alpha_multiome_rna_sobj.rds'))

In [6]:
alpha_multiome_rna_sobj@meta.data

                                 orig.ident    nCount_RNA nFeature_RNA
sample1_5_25#AAACAGCCAATAATGG-1  sample1_5_25  19067      5034
sample1_5_25#AAACAGCCAGTTGCGT-1  sample1_5_25  29913      5928
sample1_5_25#AAACAGCCATGTGGGA-1  sample1_5_25  35529      6593
sample1_5_25#AAACCGCGTTTAACGG-1  sample1_5_25  40108      6863
sample1_5_25#AAACCGGCAGCTTACA-1  sample1_5_25  39561      6650
sample1_5_25#AAACGTACAAGTGAAC-1  sample1_5_25  19601      4959
sample1_5_25#AAAGCAAGTAAGCTCA-1  sample1_5_25  14612      4430
sample1_5_25#AAAGCAAGTTGTGATG-1  sample1_5_25   8117      3276
sample1_5_25#AAAGCACCACAACCTA-1  sample1_5_25  23990      5518
sample1_5_25#AAAGCCCGTCCGCTGT-1  sample1_5_25  30249      6175
sample1_5_25#AAAGCGGGTAGGTTGC-1  sample1_5_25   6064      2702
sample1_5_25#AAAGCGGGTCACGGAT-1  sample1_5_25  24475      5650
sample1_5_25#AAAGCTTGTAAGTCGC-1  sample1_5_25  41023      7055
sample1_5_25#AAAGGAGCATAATCCG-1  sample1_5_25  31382      6261
sample1_5_25#AAAGGCTCAGTAAGTA-1  sample1_5_25  35408      6211
sample1_5_25#AACAGGATCCCGAACA-1  sample1_5_25  13819      4419
sample1_5_25#AACCGCTCACCTCACC-1  sample1_5_25  62000      8293
sample1_5_25#AACCGCTCACGTTACA-1  sample1_5_25  31652      6157
sample1_5_25#AACCGGCTCATCCTCA-1  sample1_5_25  26701      5750
sample1_5_25#AACCTAATCAATACGC-1  sample1_5_25  64049      8892
sample1_5_25#AACCTCACAACCTGGT-1  sample1_5_25  69980      8616
sample1_5_25#AACCTCACACAAAGCG-1  sample1_5_25  45077      7446
sample1_5_25#AACCTCACAGGCTAAG-1  sample1_5_25  42619      6999
sample1_5_25#AACCTCACATAATCGT-1  sample1_5_25  53933      7565
sample1_5_25#AACCTCCTCATGGCCA-1  sample1_5_25  46239      6812
sample1_5_25#AACCTTGCAAGGTGCA-1  sample1_5_25  31299      6222
sample1_5_25#AACGACAAGTCAGTAC-1  sample1_5_25   6537      2950
sample1_5_25#AACGCTAGTGATCATG-1  sample1_5_25  39672      6806
sample1_5_25#AACTGTTCATTAAACC-1  sample1_5_25  33245      6303
sample1_5_25#AACTTAGTCAGCTAAC-1  sample1_5_25  47109      7330
⋮                                ⋮             ⋮          ⋮
sample2_12_22#TTAGGCGTCAAACACC-1 sample2_12_22 17370      4858
sample2_12_22#TTAGGCTAGTAACGGA-1 sample2_12_22 20449      5269
sample2_12_22#TTATCCGTCCCGAACA-1 sample2_12_22 37150      6720
sample2_12_22#TTATCCGTCTAGCTTT-1 sample2_12_22 29814      6188
sample2_12_22#TTCAGTTTCAATCTCT-1 sample2_12_22 33671      6637
sample2_12_22#TTCCACGGTAACGAGG-1 sample2_12_22 16656      4824
sample2_12_22#TTCCTCAAGTAATCCA-1 sample2_12_22 30831      5868
sample2_12_22#TTCCTTGAGCCACATG-1 sample2_12_22 29384      6164
sample2_12_22#TTGATGTCAACCTGGT-1 sample2_12_22 30948      6091
sample2_12_22#TTGCAATCATTGCGAC-1 sample2_12_22 15642      4932
sample2_12_22#TTGCATTTCAAAGGCA-1 sample2_12_22 19248      5138
sample2_12_22#TTGCATTTCACTAAGC-1 sample2_12_22 20048      5337
sample2_12_22#TTGCTCTCAATAGTCT-1 sample2_12_22 35036      6574
sample2_12_22#TTGGAGGCAGCACGAA-1 sample2_12_22 24352      5666
sample2_12_22#TTGGAGGCATTGCAGC-1 sample2_12_22 27408      5814
sample2_12_22#TTGGGCGGTCCTAACT-1 sample2_12_22  8884      3154
sample2_12_22#TTGGGCGGTGCTCCAC-1 sample2_12_22 17216      4900
sample2_12_22#TTGTCCGGTGGAAGGC-1 sample2_12_22 17421      4945
sample2_12_22#TTGTGAGGTTCACCCA-1 sample2_12_22 19978      5230
sample2_12_22#TTGTTCCCAATAATGG-1 sample2_12_22 29546      5974
sample2_12_22#TTTAACGAGGTCCTGA-1 sample2_12_22 20548      5351
sample2_12_22#TTTAAGCCAATCATGT-1 sample2_12_22 31659      6317
sample2_12_22#TTTACGAAGGGTGAGT-1 sample2_12_22 13025      4313
sample2_12_22#TTTCAGTTCAGCCAAT-1 sample2_12_22 23096      5626
sample2_12_22#TTTCAGTTCATGCCTC-1 sample2_12_22 38472      6806
sample2_12_22#TTTCCTGAGTGAGCGG-1 sample2_12_22 17524      4998
sample2_12_22#TTTGTCCCACAGACTC-1 sample2_12_22 28469      6060
sample2_12_22#TTTGTGAAGAACCTGT-1 sample2_12_22 33078      6297
sample2_12_22#TTTGTGTTCTTTGAGA-1 sample2_12_22 16190      4347
sample2_12_22#TTTGTTGGTACTGATG-1 sample2_12_22 20682      5265
                                 Sample        TSSEnrichment ReadsInTSS
sample1_5_25#AAACAGCCAATAATGG-1  sample1_5_25   9.778        1195
sample1_5_25#AAACAGCCAGTTGCGT-1  sample1_5_25   9.022         811
sample1_5_25#AAACAGCCATGTGGGA-1  sample1_5_25   6.371        1332
sample1_5_25#AAACCGCGTTTAACGG-1  sample1_5_25   8.537        1733
sample1_5_25#AAACCGGCAGCTTACA-1  sample1_5_25   7.882        1405
sample1_5_25#AAACGTACAAGTGAAC-1  sample1_5_25   6.978          74
sample1_5_25#AAAGCAAGTAAGCTCA-1  sample1_5_25   8.113        1057
sample1_5_25#AAAGCAAGTTGTGATG-1  sample1_5_25   8.614          87
sample1_5_25#AAAGCACCACAACCTA-1  sample1_5_25   8.289        1352
sample1_5_25#AAAGCCCGTCCGCTGT-1  sample1_5_25   8.284         753
sample1_5_25#AAAGCGGGTAGGTTGC-1  sample1_5_25   9.015         824
sample1_5_25#AAAGCGGGTCACGGAT-1  sample1_5_25  10.726         130
sample1_5_25#AAAGCTTGTAAGTCGC-1  sample1_5_25   6.955         281
sample1_5_25#AAAGGAGCATAATCCG-1  sample1_5_25  10.108        1174
sample1_5_25#AAAGGCTCAGTAAGTA-1  sample1_5_25  11.094        1255
sample1_5_25#AACAGGATCCCGAACA-1  sample1_5_25  12.663        1247
sample1_5_25#AACCGCTCACCTCACC-1  sample1_5_25   9.068        2276
sample1_5_25#AACCGCTCACGTTACA-1  sample1_5_25  11.060        1279
sample1_5_25#AACCGGCTCATCCTCA-1  sample1_5_25   9.793        1266
sample1_5_25#AACCTAATCAATACGC-1  sample1_5_25   7.869         151
sample1_5_25#AACCTCACAACCTGGT-1  sample1_5_25   9.842        1988
sample1_5_25#AACCTCACACAAAGCG-1  sample1_5_25  10.680        2578
sample1_5_25#AACCTCACAGGCTAAG-1  sample1_5_25  10.522         898
sample1_5_25#AACCTCACATAATCGT-1  sample1_5_25   8.585        1305
sample1_5_25#AACCTCCTCATGGCCA-1  sample1_5_25  11.881         330
sample1_5_25#AACCTTGCAAGGTGCA-1  sample1_5_25  11.152         918
sample1_5_25#AACGACAAGTCAGTAC-1  sample1_5_25   5.866        1019
sample1_5_25#AACGCTAGTGATCATG-1  sample1_5_25   7.627         104
sample1_5_25#AACTGTTCATTAAACC-1  sample1_5_25  10.102         653
sample1_5_25#AACTTAGTCAGCTAAC-1  sample1_5_25   9.191        1295
⋮                                ⋮             ⋮             ⋮
sample2_12_22#TTAGGCGTCAAACACC-1 sample2_12_22  7.921        1784
sample2_12_22#TTAGGCTAGTAACGGA-1 sample2_12_22 13.213        2956
sample2_12_22#TTATCCGTCCCGAACA-1 sample2_12_22  7.893        1726
sample2_12_22#TTATCCGTCTAGCTTT-1 sample2_12_22  9.031        1359
sample2_12_22#TTCAGTTTCAATCTCT-1 sample2_12_22  8.120        1427
sample2_12_22#TTCCACGGTAACGAGG-1 sample2_12_22  8.713         132
sample2_12_22#TTCCTCAAGTAATCCA-1 sample2_12_22 10.168        1674
sample2_12_22#TTCCTTGAGCCACATG-1 sample2_12_22 10.141        1562
sample2_12_22#TTGATGTCAACCTGGT-1 sample2_12_22  9.215        1638
sample2_12_22#TTGCAATCATTGCGAC-1 sample2_12_22  9.116        1266
sample2_12_22#TTGCATTTCAAAGGCA-1 sample2_12_22  9.428        1614
sample2_12_22#TTGCATTTCACTAAGC-1 sample2_12_22  5.899        1573
sample2_12_22#TTGCTCTCAATAGTCT-1 sample2_12_22  9.474         799
sample2_12_22#TTGGAGGCAGCACGAA-1 sample2_12_22  7.534        1773
sample2_12_22#TTGGAGGCATTGCAGC-1 sample2_12_22  4.828        1492
sample2_12_22#TTGGGCGGTCCTAACT-1 sample2_12_22  5.800         782
sample2_12_22#TTGGGCGGTGCTCCAC-1 sample2_12_22  7.765        1498
sample2_12_22#TTGTCCGGTGGAAGGC-1 sample2_12_22  8.939        1616
sample2_12_22#TTGTGAGGTTCACCCA-1 sample2_12_22  8.908        1786
sample2_12_22#TTGTTCCCAATAATGG-1 sample2_12_22  6.842        1745
sample2_12_22#TTTAACGAGGTCCTGA-1 sample2_12_22  9.603        1678
sample2_12_22#TTTAAGCCAATCATGT-1 sample2_12_22 10.069        1378
sample2_12_22#TTTACGAAGGGTGAGT-1 sample2_12_22  8.869        1478
sample2_12_22#TTTCAGTTCAGCCAAT-1 sample2_12_22  8.757        1623
sample2_12_22#TTTCAGTTCATGCCTC-1 sample2_12_22  7.111         237
sample2_12_22#TTTCCTGAGTGAGCGG-1 sample2_12_22  6.488        1920
sample2_12_22#TTTGTCCCACAGACTC-1 sample2_12_22 10.147        1486
sample2_12_22#TTTGTGAAGAACCTGT-1 sample2_12_22  7.970        1630
sample2_12_22#TTTGTGTTCTTTGAGA-1 sample2_12_22  8.273        1199
sample2_12_22#TTTGTTGGTACTGATG-1 sample2_12_22  9.610        1553
                                 ReadsInPromoter ReadsInBlacklist PromoterRatio
sample1_5_25#AAACAGCCAATAATGG-1   4790            570             0.12498043
sample1_5_25#AAACAGCCAGTTGCGT-1   3357            376             0.12552348
sample1_5_25#AAACAGCCATGTGGGA-1   6123           1049             0.08965123
sample1_5_25#AAACCGCGTTTAACGG-1   7200           1083             0.10369858
sample1_5_25#AAACCGGCAGCTTACA-1   5910            742             0.10378618
sample1_5_25#AAACGTACAAGTGAAC-1    262             29             0.11302847
sample1_5_25#AAAGCAAGTAAGCTCA-1   4764            575             0.10769996
sample1_5_25#AAAGCAAGTTGTGATG-1    322             38             0.13597973
sample1_5_25#AAAGCACCACAACCTA-1   5975            968             0.10995988
sample1_5_25#AAAGCCCGTCCGCTGT-1   3388            431             0.10171731
sample1_5_25#AAAGCGGGTAGGTTGC-1   3432            398             0.10927848
sample1_5_25#AAAGCGGGTCACGGAT-1    492             78             0.10012210
sample1_5_25#AAAGCTTGTAAGTCGC-1   1175            164             0.10489198
sample1_5_25#AAAGGAGCATAATCCG-1   5031            524             0.12622309
sample1_5_25#AAAGGCTCAGTAAGTA-1   5255            625             0.11517556
sample1_5_25#AACAGGATCCCGAACA-1   4595            532             0.13195681
sample1_5_25#AACCGCTCACCTCACC-1   9697           1116             0.11611505
sample1_5_25#AACCGCTCACGTTACA-1   5173            647             0.12146044
sample1_5_25#AACCGGCTCATCCTCA-1   5319            594             0.10673436
sample1_5_25#AACCTAATCAATACGC-1    655             98             0.10751806
sample1_5_25#AACCTCACAACCTGGT-1   8081            984             0.12833910
sample1_5_25#AACCTCACACAAAGCG-1  10212           1228             0.13182217
sample1_5_25#AACCTCACAGGCTAAG-1   3869            404             0.12332653
sample1_5_25#AACCTCACATAATCGT-1   5693            678             0.11133492
sample1_5_25#AACCTCCTCATGGCCA-1   1183            143             0.11429952
sample1_5_25#AACCTTGCAAGGTGCA-1   3452            383             0.12837486
sample1_5_25#AACGACAAGTCAGTAC-1   4771            906             0.08288742
sample1_5_25#AACGCTAGTGATCATG-1    424             56             0.11041667
sample1_5_25#AACTGTTCATTAAACC-1   2649            303             0.12435452
sample1_5_25#AACTTAGTCAGCTAAC-1   5338            630             0.10759494
⋮                                ⋮               ⋮                ⋮
sample2_12_22#TTAGGCGTCAAACACC-1  7628           1017             0.10622772
sample2_12_22#TTAGGCTAGTAACGGA-1 11080           1192             0.15662548
sample2_12_22#TTATCCGTCCCGAACA-1  7466            956             0.10647461
sample2_12_22#TTATCCGTCTAGCTTT-1  5716            634             0.11741024
sample2_12_22#TTCAGTTTCAATCTCT-1  5767            730             0.10770581
sample2_12_22#TTCCACGGTAACGAGG-1   578             62             0.10852422
sample2_12_22#TTCCTCAAGTAATCCA-1  6824            794             0.13230960
sample2_12_22#TTCCTTGAGCCACATG-1  6558            667             0.12484770
sample2_12_22#TTGATGTCAACCTGGT-1  6939            762             0.12225589
sample2_12_22#TTGCAATCATTGCGAC-1  5128            724             0.12029087
sample2_12_22#TTGCATTTCAAAGGCA-1  6621            793             0.12658688
sample2_12_22#TTGCATTTCACTAAGC-1  7314           1085             0.10254613
sample2_12_22#TTGCTCTCAATAGTCT-1  3248            297             0.14198286
sample2_12_22#TTGGAGGCAGCACGAA-1  7878           1308             0.09414211
sample2_12_22#TTGGAGGCATTGCAGC-1  7604           1304             0.07196396
sample2_12_22#TTGGGCGGTCCTAACT-1  3750            665             0.08439483
sample2_12_22#TTGGGCGGTGCTCCAC-1  6674            994             0.09996106
sample2_12_22#TTGTCCGGTGGAAGGC-1  6292            814             0.10927026
sample2_12_22#TTGTGAGGTTCACCCA-1  7451            949             0.11146849
sample2_12_22#TTGTTCCCAATAATGG-1  7790           1118             0.09399131
sample2_12_22#TTTAACGAGGTCCTGA-1  6997            761             0.13228844
sample2_12_22#TTTAAGCCAATCATGT-1  5661            749             0.11456731
sample2_12_22#TTTACGAAGGGTGAGT-1  6121            778             0.10912430
sample2_12_22#TTTCAGTTCAGCCAAT-1  6765            969             0.11288923
sample2_12_22#TTTCAGTTCATGCCTC-1  1035            132             0.11279425
sample2_12_22#TTTCCTGAGTGAGCGG-1  8767           1236             0.08991057
sample2_12_22#TTTGTCCCACAGACTC-1  6130            711             0.11670411
sample2_12_22#TTTGTGAAGAACCTGT-1  6998            993             0.10479185
sample2_12_22#TTTGTGTTCTTTGAGA-1  5118            774             0.11224176
sample2_12_22#TTTGTTGGTACTGATG-1  6377            763             0.11917844
                                 PassQC ⋯ Gex_RiboRatio Stage    Clusters
sample1_5_25#AAACAGCCAATAATGG-1  1      ⋯ 0             control  C5
sample1_5_25#AAACAGCCAGTTGCGT-1  1      ⋯ 0             control  C5
sample1_5_25#AAACAGCCATGTGGGA-1  1      ⋯ 0             mid-late C3
sample1_5_25#AAACCGCGTTTAACGG-1  1      ⋯ 0             mid-late C1
sample1_5_25#AAACCGGCAGCTTACA-1  1      ⋯ 0             mid-late C2
sample1_5_25#AAACGTACAAGTGAAC-1  1      ⋯ 0             control  C4
sample1_5_25#AAAGCAAGTAAGCTCA-1  1      ⋯ 0             control  C5
sample1_5_25#AAAGCAAGTTGTGATG-1  1      ⋯ 0             mid-late C5
sample1_5_25#AAAGCACCACAACCTA-1  1      ⋯ 0             mid-late C2
sample1_5_25#AAAGCCCGTCCGCTGT-1  1      ⋯ 0             mid-late C5
sample1_5_25#AAAGCGGGTAGGTTGC-1  1      ⋯ 0             control  C2
sample1_5_25#AAAGCGGGTCACGGAT-1  1      ⋯ 0             control  C3
sample1_5_25#AAAGCTTGTAAGTCGC-1  1      ⋯ 0             mid-late C4
sample1_5_25#AAAGGAGCATAATCCG-1  1      ⋯ 0             control  C5
sample1_5_25#AAAGGCTCAGTAAGTA-1  1      ⋯ 0             mid-late C5
sample1_5_25#AACAGGATCCCGAACA-1  1      ⋯ 0             control  C5
sample1_5_25#AACCGCTCACCTCACC-1  1      ⋯ 0             mid-late C4
sample1_5_25#AACCGCTCACGTTACA-1  1      ⋯ 0             control  C5
sample1_5_25#AACCGGCTCATCCTCA-1  1      ⋯ 0             control  C2
sample1_5_25#AACCTAATCAATACGC-1  1      ⋯ 0             mid-late C3
sample1_5_25#AACCTCACAACCTGGT-1  1      ⋯ 0             mid-late C4
sample1_5_25#AACCTCACACAAAGCG-1  1      ⋯ 0             mid-late C4
sample1_5_25#AACCTCACAGGCTAAG-1  1      ⋯ 0             control  C5
sample1_5_25#AACCTCACATAATCGT-1  1      ⋯ 0             control  C3
sample1_5_25#AACCTCCTCATGGCCA-1  1      ⋯ 0             control  C5
sample1_5_25#AACCTTGCAAGGTGCA-1  1      ⋯ 0             mid-late C4
sample1_5_25#AACGACAAGTCAGTAC-1  1      ⋯ 0             mid-late C5
sample1_5_25#AACGCTAGTGATCATG-1  1      ⋯ 0             control  C5
sample1_5_25#AACTGTTCATTAAACC-1  1      ⋯ 0             control  C3
sample1_5_25#AACTTAGTCAGCTAAC-1  1      ⋯ 0             mid-late C2
⋮                                ⋮      ⋱ ⋮             ⋮        ⋮
sample2_12_22#TTAGGCGTCAAACACC-1 1      ⋯ 0             control  C2
sample2_12_22#TTAGGCTAGTAACGGA-1 1      ⋯ 0             early    C1
sample2_12_22#TTATCCGTCCCGAACA-1 1      ⋯ 0             control  C3
sample2_12_22#TTATCCGTCTAGCTTT-1 1      ⋯ 0             control  C3
sample2_12_22#TTCAGTTTCAATCTCT-1 1      ⋯ 0             control  C5
sample2_12_22#TTCCACGGTAACGAGG-1 1      ⋯ 0             early    C5
sample2_12_22#TTCCTCAAGTAATCCA-1 1      ⋯ 0             control  C5
sample2_12_22#TTCCTTGAGCCACATG-1 1      ⋯ 0             control  C2
sample2_12_22#TTGATGTCAACCTGGT-1 1      ⋯ 0             control  C2
sample2_12_22#TTGCAATCATTGCGAC-1 1      ⋯ 0             early    C4
sample2_12_22#TTGCATTTCAAAGGCA-1 1      ⋯ 0             early    C1
sample2_12_22#TTGCATTTCACTAAGC-1 1      ⋯ 0             early    C4
sample2_12_22#TTGCTCTCAATAGTCT-1 1      ⋯ 0             control  C5
sample2_12_22#TTGGAGGCAGCACGAA-1 1      ⋯ 0             control  C3
sample2_12_22#TTGGAGGCATTGCAGC-1 1      ⋯ 0             control  C3
sample2_12_22#TTGGGCGGTCCTAACT-1 1      ⋯ 0             early    C2
sample2_12_22#TTGGGCGGTGCTCCAC-1 1      ⋯ 0             control  C3
sample2_12_22#TTGTCCGGTGGAAGGC-1 1      ⋯ 0             control  C2
sample2_12_22#TTGTGAGGTTCACCCA-1 1      ⋯ 0             early    C5
sample2_12_22#TTGTTCCCAATAATGG-1 1      ⋯ 0             early    C3
sample2_12_22#TTTAACGAGGTCCTGA-1 1      ⋯ 0             early    C3
sample2_12_22#TTTAAGCCAATCATGT-1 1      ⋯ 0             control  C3
sample2_12_22#TTTACGAAGGGTGAGT-1 1      ⋯ 0             early    C3
sample2_12_22#TTTCAGTTCAGCCAAT-1 1      ⋯ 0             control  C5
sample2_12_22#TTTCAGTTCATGCCTC-1 1      ⋯ 0             control  C5
sample2_12_22#TTTCCTGAGTGAGCGG-1 1      ⋯ 0             control  C3
sample2_12_22#TTTGTCCCACAGACTC-1 1      ⋯ 0             control  C2
sample2_12_22#TTTGTGAAGAACCTGT-1 1      ⋯ 0             control  C3
sample2_12_22#TTTGTGTTCTTTGAGA-1 1      ⋯ 0             early    C1
sample2_12_22#TTTGTTGGTACTGATG-1 1      ⋯ 0             early    C2
                                 cell_class          cell_class_UMAP_labels
sample1_5_25#AAACAGCCAATAATGG-1  Cholinergic Neurons Cholinergic Neurons
sample1_5_25#AAACAGCCAGTTGCGT-1  Cholinergic Neurons Cholinergic Neurons
sample1_5_25#AAACAGCCATGTGGGA-1  Cholinergic Neurons Cholinergic Neurons
sample1_5_25#AAACCGCGTTTAACGG-1  Cholinergic Neurons Cholinergic Neurons
sample1_5_25#AAACCGGCAGCTTACA-1  Cholinergic Neurons Cholinergic Neurons
sample1_5_25#AAACGTACAAGTGAAC-1  Cholinergic Neurons Cholinergic Neurons
sample1_5_25#AAAGCAAGTAAGCTCA-1  Cholinergic Neurons Cholinergic Neurons
sample1_5_25#AAAGCAAGTTGTGATG-1  Cholinergic Neurons Cholinergic Neurons
sample1_5_25#AAAGCACCACAACCTA-1  Cholinergic Neurons Cholinergic Neurons
sample1_5_25#AAAGCCCGTCCGCTGT-1  Cholinergic Neurons Cholinergic Neurons
sample1_5_25#AAAGCGGGTAGGTTGC-1  Cholinergic Neurons Cholinergic Neurons
sample1_5_25#AAAGCGGGTCACGGAT-1  Cholinergic Neurons Cholinergic Neurons
sample1_5_25#AAAGCTTGTAAGTCGC-1  Cholinergic Neurons Cholinergic Neurons
sample1_5_25#AAAGGAGCATAATCCG-1  Cholinergic Neurons Cholinergic Neurons
sample1_5_25#AAAGGCTCAGTAAGTA-1  Cholinergic Neurons Cholinergic Neurons
sample1_5_25#AACAGGATCCCGAACA-1  Cholinergic Neurons Cholinergic Neurons
sample1_5_25#AACCGCTCACCTCACC-1  Cholinergic Neurons Cholinergic Neurons
sample1_5_25#AACCGCTCACGTTACA-1  Cholinergic Neurons Cholinergic Neurons
sample1_5_25#AACCGGCTCATCCTCA-1  Cholinergic Neurons Cholinergic Neurons
sample1_5_25#AACCTAATCAATACGC-1  Cholinergic Neurons Cholinergic Neurons
sample1_5_25#AACCTCACAACCTGGT-1  Cholinergic Neurons Cholinergic Neurons
sample1_5_25#AACCTCACACAAAGCG-1  Cholinergic Neurons Cholinergic Neurons
sample1_5_25#AACCTCACAGGCTAAG-1  Cholinergic Neurons Cholinergic Neurons
sample1_5_25#AACCTCACATAATCGT-1  Cholinergic Neurons Cholinergic Neurons
sample1_5_25#AACCTCCTCATGGCCA-1  Cholinergic Neurons Cholinergic Neurons
sample1_5_25#AACCTTGCAAGGTGCA-1  Cholinergic Neurons Cholinergic Neurons
sample1_5_25#AACGACAAGTCAGTAC-1  Cholinergic Neurons Cholinergic Neurons
sample1_5_25#AACGCTAGTGATCATG-1  Cholinergic Neurons Cholinergic Neurons
sample1_5_25#AACTGTTCATTAAACC-1  Cholinergic Neurons Cholinergic Neurons
sample1_5_25#AACTTAGTCAGCTAAC-1  Cholinergic Neurons Cholinergic Neurons
⋮                                ⋮                   ⋮
sample2_12_22#TTAGGCGTCAAACACC-1 Cholinergic Neurons Cholinergic Neurons
sample2_12_22#TTAGGCTAGTAACGGA-1 Cholinergic Neurons Cholinergic Neurons
sample2_12_22#TTATCCGTCCCGAACA-1 Cholinergic Neurons Cholinergic Neurons
sample2_12_22#TTATCCGTCTAGCTTT-1 Cholinergic Neurons Cholinergic Neurons
sample2_12_22#TTCAGTTTCAATCTCT-1 Cholinergic Neurons Cholinergic Neurons
sample2_12_22#TTCCACGGTAACGAGG-1 Cholinergic Neurons Cholinergic Neurons
sample2_12_22#TTCCTCAAGTAATCCA-1 Cholinergic Neurons Cholinergic Neurons
sample2_12_22#TTCCTTGAGCCACATG-1 Cholinergic Neurons Cholinergic Neurons
sample2_12_22#TTGATGTCAACCTGGT-1 Cholinergic Neurons Cholinergic Neurons

In [8]:
alpha_multiome_rna_sobj$damn_status <- ifelse(alpha_multiome_rna_sobj$alpha_subtype %in% c("Early DAMN", "Late DAMN"), "DAMN", "nonDAMN")

In [9]:
# Prepare counts for the Seurat object
alpha.counts.split <- prepare_counts(alpha_multiome_rna_sobj, test.category='damn_status', 
                                           by.category='damn_status', min.nuclei = 50)

In [10]:
counts <- cbind(alpha.counts.split[[1]], alpha.counts.split[[2]])

In [12]:
head(counts)

        DAMN_sample1_12_22 DAMN_sample1_5_25 DAMN_sample1_6_3
Gm1992    24                 82               127
Gm19938   51                189               176
Xkr4    1809               6426              5030
Gm37381    0                  0                 1
Rp1        1                  2                 2
Sox17      0                  0                 0
        DAMN_sample2_12_22 DAMN_sample2_6_3 nonDAMN_sample1_12_22
Gm1992    39                 54               207
Gm19938   38                162               539
Xkr4    1327               3842             19982
Gm37381    1                  0                 0
Rp1        3                  3                 9
Sox17      0                  0                 0
        nonDAMN_sample1_5_25 nonDAMN_sample1_6_3 nonDAMN_sample2_12_22
Gm1992    304                 129                  625
Gm19938   736                 184                  444
Xkr4    27932                5308                15123
Gm37381     1                   0                    0
Rp1        16                   3                   10
Sox17       0                   0                    0
        nonDAMN_sample2_6_3
Gm1992   145
Gm19938  343
Xkr4    8409
Gm37381    1
Rp1       11
Sox17      0

In [13]:
# Create a data frame of sample information
colData <- data.frame(samples = colnames(counts))
colData

   samples
1  DAMN_sample1_12_22
2  DAMN_sample1_5_25
3  DAMN_sample1_6_3
4  DAMN_sample2_12_22
5  DAMN_sample2_6_3
6  nonDAMN_sample1_12_22
7  nonDAMN_sample1_5_25
8  nonDAMN_sample1_6_3
9  nonDAMN_sample2_12_22
10 nonDAMN_sample2_6_3

In [14]:
# Add a condition column containing the test.category information (ex: cell class) for each sample
colData$condition <- sub("_.*", "", colData$samples) 
colData

   samples               condition
1  DAMN_sample1_12_22    DAMN
2  DAMN_sample1_5_25     DAMN
3  DAMN_sample1_6_3      DAMN
4  DAMN_sample2_12_22    DAMN
5  DAMN_sample2_6_3      DAMN
6  nonDAMN_sample1_12_22 nonDAMN
7  nonDAMN_sample1_5_25  nonDAMN
8  nonDAMN_sample1_6_3   nonDAMN
9  nonDAMN_sample2_12_22 nonDAMN
10 nonDAMN_sample2_6_3   nonDAMN

In [15]:
# Convert the sample names to row names
colData <- colData %>% column_to_rownames(var = "samples")
colData

                      condition
DAMN_sample1_12_22    DAMN
DAMN_sample1_5_25     DAMN
DAMN_sample1_6_3      DAMN
DAMN_sample2_12_22    DAMN
DAMN_sample2_6_3      DAMN
nonDAMN_sample1_12_22 nonDAMN
nonDAMN_sample1_5_25  nonDAMN
nonDAMN_sample1_6_3   nonDAMN
nonDAMN_sample2_12_22 nonDAMN
nonDAMN_sample2_6_3   nonDAMN

In [16]:
# Create DESEq object
dds <- DESeqDataSetFromMatrix(countData = counts,
                      colData = colData,
                      design = ~ condition)

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”

In [17]:
# Run DESeq
dds <- DESeq(dds, minReplicatesForReplace = Inf)

estimating size factors

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

final dispersion estimates

fitting model and testing

In [18]:
results_name <- resultsNames(dds)
results_name <- results_name[grep("^condition", results_name)]
results_name

[1] "condition_nonDAMN_vs_DAMN"

In [19]:
savedir.path <- paste0(save_dir, 'DESeq2/')

res <- results(dds, name = results_name) %>% data.frame(.) 
res$gene <- rownames(res)
res <- res %>% arrange(padj) %>% filter(!is.na(padj))
rownames(res) <- res$gene
res <- dplyr::select(res, -gene)
write.csv(res, file=paste0(savedir.path, "alpha_multiome_RNA_", sub("^[^_]*_", "", results_name), '.csv'))

### DAI vs. Non-cholinergic interneurons from multiome RNA data
multiome_RNA_Non.Cholinergic.Interneurons_vs_Disease.Associated.Interneurons.csv

In [39]:
proj_all_dr_multiome_rna_sobj <- readRDS(file = paste0(save_dir, 'rds_files/proj_all_dr_multiome_rna_sobj.rds'))

In [40]:
dai_cholInt_multiome_rna_sobj <- subset(proj_all_dr_multiome_rna_sobj, subset = cell_class %in% c('Disease-Associated Interneurons','Non-Cholinergic Interneurons'))

In [53]:
# Prepare counts for the Seurat object
counts.split <- prepare_counts(dai_cholInt_multiome_rna_sobj, test.category='cell_class', 
                                           by.category='cell_class', min.nuclei = 15)

In [54]:
counts <- cbind(counts.split[[1]], counts.split[[2]])

In [55]:
head(counts)

        Disease-Associated Interneurons_sample1_5_25
Gm1992    3
Gm19938   3
Xkr4    241
Gm37381   0
Rp1       0
Sox17     0
        Disease-Associated Interneurons_sample1_6_3
Gm1992    7
Gm19938   3
Xkr4    167
Gm37381   0
Rp1       0
Sox17     0
        Disease-Associated Interneurons_sample2_6_3
Gm1992    5
Gm19938  29
Xkr4    680
Gm37381   0
Rp1       0
Sox17     0
        Non-Cholinergic Interneurons_sample1_12_22
Gm1992   100
Gm19938  260
Xkr4    9031
Gm37381    0
Rp1        5
Sox17      0
        Non-Cholinergic Interneurons_sample1_5_25
Gm1992    131
Gm19938   456
Xkr4    17308
Gm37381     1
Rp1         3
Sox17       0
        Non-Cholinergic Interneurons_sample1_6_3
Gm1992    300
Gm19938   496
Xkr4    12208
Gm37381     0
Rp1         7
Sox17       0
        Non-Cholinergic Interneurons_sample2_12_22
Gm1992   239
Gm19938  250
Xkr4    7908
Gm37381    0
Rp1        3
Sox17      0
        Non-Cholinergic Interneurons_sample2_6_3
Gm1992    322
Gm19938   908
Xkr4    20546
Gm37381     0
Rp1         8
Sox17       0

In [56]:
# Create a data frame of sample information
colData <- data.frame(samples = colnames(counts))
colData

  samples
1 Disease-Associated Interneurons_sample1_5_25
2 Disease-Associated Interneurons_sample1_6_3
3 Disease-Associated Interneurons_sample2_6_3
4 Non-Cholinergic Interneurons_sample1_12_22
5 Non-Cholinergic Interneurons_sample1_5_25
6 Non-Cholinergic Interneurons_sample1_6_3
7 Non-Cholinergic Interneurons_sample2_12_22
8 Non-Cholinergic Interneurons_sample2_6_3

In [57]:
# Add a condition column containing the test.category information (ex: cell class) for each sample
colData$condition <- sub("_.*", "", colData$samples) 
colData

  samples                                      condition
1 Disease-Associated Interneurons_sample1_5_25 Disease-Associated Interneurons
2 Disease-Associated Interneurons_sample1_6_3  Disease-Associated Interneurons
3 Disease-Associated Interneurons_sample2_6_3  Disease-Associated Interneurons
4 Non-Cholinergic Interneurons_sample1_12_22   Non-Cholinergic Interneurons
5 Non-Cholinergic Interneurons_sample1_5_25    Non-Cholinergic Interneurons
6 Non-Cholinergic Interneurons_sample1_6_3     Non-Cholinergic Interneurons
7 Non-Cholinergic Interneurons_sample2_12_22   Non-Cholinergic Interneurons
8 Non-Cholinergic Interneurons_sample2_6_3     Non-Cholinergic Interneurons

In [58]:
# Convert the sample names to row names
colData <- colData %>% column_to_rownames(var = "samples")
colData

                                             condition
Disease-Associated Interneurons_sample1_5_25 Disease-Associated Interneurons
Disease-Associated Interneurons_sample1_6_3  Disease-Associated Interneurons
Disease-Associated Interneurons_sample2_6_3  Disease-Associated Interneurons
Non-Cholinergic Interneurons_sample1_12_22   Non-Cholinergic Interneurons
Non-Cholinergic Interneurons_sample1_5_25    Non-Cholinergic Interneurons
Non-Cholinergic Interneurons_sample1_6_3     Non-Cholinergic Interneurons
Non-Cholinergic Interneurons_sample2_12_22   Non-Cholinergic Interneurons
Non-Cholinergic Interneurons_sample2_6_3     Non-Cholinergic Interneurons

In [59]:
# Create DESEq object
dds <- DESeqDataSetFromMatrix(countData = counts,
                      colData = colData,
                      design = ~ condition)

converting counts to integer mode

Warning message in DESeqDataSet(se, design = design, ignoreRank):
“some variables in design formula are characters, converting to factors”
  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

In [60]:
# Run DESeq
dds <- DESeq(dds, minReplicatesForReplace = Inf)

estimating size factors

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

estimating dispersions

gene-wise dispersion estimates

mean-dispersion relationship

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

final dispersion estimates

  Note: levels of factors in the design contain characters other than
  letters, numbers, '_' and '.'. It is recommended (but not required) to use
  only letters, numbers, and delimiters '_' or '.', as these are safe characters
  for column names in R. [This is a message, not a warning or an error]

fitting model and testing

In [61]:
results_name <- resultsNames(dds)
results_name <- results_name[grep("^condition", results_name)]
results_name

[1] "condition_Non.Cholinergic.Interneurons_vs_Disease.Associated.Interneurons"

In [62]:
savedir.path <- paste0(save_dir, 'DESeq2/')

res <- results(dds, name = results_name) %>% data.frame(.) 
res$gene <- rownames(res)
res <- res %>% arrange(padj) %>% filter(!is.na(padj))
rownames(res) <- res$gene
res <- dplyr::select(res, -gene)
write.csv(res, file=paste0(savedir.path, "multiome_RNA_", sub("^[^_]*_", "", results_name), '.csv'))